### ISSUE TITLE
suggestion: as a user a want to see the cheapest price in history

### ISSUE THREAD

**Issue by solygen** [lx4r/chames#1]
Might be neat to store/show the lowest recorded price of a game.

**Comment by lx4r** [comment]
That's a very good idea!
My only concern is that it would require a bigger database setup and and initially I wanted this project to be as lightweight as possible.
A compromise could be to make the price history tracking optional and maybe try to limit the file size by e.g. only keeping price recorda for the last 30 days.
What do you think?

**Comment by solygen** [comment]
Wouldn't it be possible just to add one "datebase field" containing the cheapest price? IMHO a complete history isn't that important. Or do i missed you point?

**Comment by lx4r** [comment]
Ah, sorry, I misunderstood you. I agree with you on the history.
That wouldn't be so hard hard to implement then, I'll add it to my todo list.

**Comment by lx4r** [comment]
@solygen I'm working on this feature. What do you think about this way of showing the lowest price? Also considered a tooltip ...
<img width="181" alt="bildschirmfoto 2016-08-02 um 12 44 10" src="https://cloud.githubusercontent.com/assets/1402895/17326007/f47f3198-58ae-11e6-81f5-2b80be146391.png">
