### ISSUE TITLE
new structure of G2A website breaks Chames

### ISSUE THREAD

**Issue by razza-guhl** [lx4r/chames#14]
Hi,

I justed installed chames on localhost. Seems like all freshly added games were unavaible.

Does Chames still works? Seems like G2A changed the URL-structure (there is no product_id on their html code)

**Comment by lx4r** [comment]
Hey,
thanks for reporting the error. Sadly I don't have time to check on Chames at the moment but I hopfully will in a few weeks.

In the meantime: Let me know if you find out more about G2A's new site structure.

**Comment by razza-guhl** [comment]
Thank you. I will give you feedback as soon as i know more.

**Comment by PLexxa** [comment]
productID replaced with "MagentoID":xxxxx in page code.

**Comment by lx4r** [comment]
@PLexxa Thanks a lot for the update!
If I find the time I'll continue working on a node.js powered version of Chames to learn some more JS (that version will include the new ID) and also update the PHP version.
If anybody has some time and PHP knowledge on their hands right now a pull request would of course also be appreciated. :)

**Comment by lx4r** [comment]
fixed by merging #15, remaining problem with the country code will be tracked in #16
